tracer:
  property: "{cipher} e9c1f7c7b877c0e121bbc179e354049900dbc71bd5e69673b218b00d5b4b1193"
spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform:  postgres
    url: jdbc:postgresql://database:5432/eagle_eye_local
    username: postgres
    password: p0stgr@s
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
    
