tracer:
  property: {cipher} 020070848a16c87dd827f2ab0c175d8a9a6b5b0c96541d491c2ce2ee175b20f6
spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform:  postgres
    url: jdbc:postgresql://database:5432/eagle_eye_local
    username: postgres
    password: p0stgr@s
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
    
